Select title , length , movieexec.NAME FROM MOVIE , MOVIEEXEC , MOVIESTAR , STARSIN
WHERE '1970-01-01' > BIRTHDATE AND MOVIESTAR.ADDRESS LIKE LOWER('%CALIFORNIA%') AND MOVIESTAR.NAME = STARNAME AND PRODUCERNO = CERTNO AND MOVIETITLE = TITLE AND GENDER = LOWER('FEMALE')
ORDER BY TITLE , LENGTH DESC, TITLE;