Select name , birthdate FROM MOVIESTAR , STARSIN
WHERE (MOVIETITLE LIKE LOWER ('%AND%') OR MOVIETITLE LIKE LOWER('%OF%')) AND STARNAME = NAME

MINUS

Select name , birthdate FROM MOVIESTAR , STARSIN
WHERE (MOVIETITLE LIKE LOWER ('%AND%') AND MOVIETITLE LIKE LOWER('%OF%')) AND STARNAME = NAME

UNION

Select name , birthdate FROM MOVIESTAR , STARSIN, MOVIE
WHERE ((((YEAR = '1980' AND TITLE = MOVIETITLE) AND YEAR = MOVIEYEAR) AND STARNAME = NAME) AND MOVIETITLE NOT LIKE LOWER('%AND%')) AND MOVIETITLE NOT LIKE LOWER('%OF%')
ORDER BY birthdate desc;